#!/usr/bin/env python3
"""City world generator: grid-of-blocks Gazebo city for the Limo Pro.

Emits four mutually consistent artifacts from one parameter set:

  simulation/worlds/city_blocks.sdf         world: roads, buildings, walls,
                                            pedestrian + vehicle actors
  simulation/models/city_textures/          procedural PBR albedo maps
  config/maps/city_blocks_roadmap.yaml      street-grid node-link roadmap
                                            (planner frame = world - spawn)
  config/scenarios/city_patrol.yaml         looping patrol over the outer ring

Layout: (blocks x blocks) city blocks separated by streets. Street
centerlines form the roadmap graph; the robot spawns at the west
intersection of row `blocks//2`, facing east, which anchors the planner
frame. Everything is limo-scale (~1/10 of a real city).

Actors are kinematic (no collision geometry) but visible to the gpu_lidar,
so the stack must avoid them perceptually — same contract as the existing
town_actors.sdf pedestrians. Vehicles keep right-hand traffic: each loops
its circuit counter-clockwise with a right-lane offset.

Usage:
  python3 simulation/gen_city_world.py            # defaults (3x3, seed 7)
  python3 simulation/gen_city_world.py --blocks 4 --seed 3 --no-textures
"""

import argparse
import math
import random
import struct
import zlib
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Procedural PNG textures (stdlib-only PNG writer)
# ---------------------------------------------------------------------------


def _png_bytes(width, height, rgb_rows):
    """Encode 8-bit RGB rows (list of bytearrays) as a PNG file."""

    def chunk(tag, data):
        block = tag + data
        return struct.pack(">I", len(data)) + block + struct.pack(
            ">I", zlib.crc32(block) & 0xFFFFFFFF
        )

    raw = b"".join(b"\x00" + bytes(row) for row in rgb_rows)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 6))
        + chunk(b"IEND", b"")
    )


def _facade_texture(rng, base, size=256, cols=6, rows=8):
    """Building facade: base wall color with a grid of windows, some lit."""
    rows_px = []
    cell_w, cell_h = size // cols, size // rows
    win_margin_x, win_margin_y = cell_w // 4, cell_h // 4
    lit = {
        (c, r)
        for c in range(cols)
        for r in range(rows)
        if rng.random() < 0.18
    }
    for y in range(size):
        row = bytearray()
        for x in range(size):
            c, r = x // cell_w, y // cell_h
            in_win = (
                c < cols
                and r < rows
                and win_margin_x <= x - c * cell_w < cell_w - win_margin_x
                and win_margin_y <= y - r * cell_h < cell_h - win_margin_y
            )
            if in_win:
                px = (245, 220, 130) if (c, r) in lit else (38, 52, 70)
            else:
                n = rng.randint(-6, 6)
                px = tuple(max(0, min(255, v + n)) for v in base)
            row.extend(px)
        rows_px.append(row)
    return _png_bytes(size, size, rows_px)


def _noise_texture(rng, base, spread, size=256):
    """Flat noisy surface (asphalt, concrete)."""
    rows_px = []
    for _ in range(size):
        row = bytearray()
        for _ in range(size):
            n = rng.randint(-spread, spread)
            row.extend(max(0, min(255, v + n)) for v in base)
        rows_px.append(row)
    return _png_bytes(size, size, rows_px)


FACADE_BASES = [
    (168, 148, 122),  # sandstone
    (140, 148, 158),  # steel gray
    (150, 118, 100),  # brick brown
    (128, 142, 128),  # sage
    (172, 160, 150),  # limestone
]


def write_textures(rng, tex_dir):
    tex_dir.mkdir(parents=True, exist_ok=True)
    (tex_dir / "model.config").write_text(
        '<?xml version="1.0"?>\n'
        "<model>\n"
        "  <name>city_textures</name>\n"
        "  <version>1.0</version>\n"
        "  <description>Procedural textures for city_blocks.sdf "
        "(generated by gen_city_world.py)</description>\n"
        "</model>\n"
    )
    for i, base in enumerate(FACADE_BASES):
        (tex_dir / f"facade_{i}.png").write_bytes(_facade_texture(rng, base))
    (tex_dir / "asphalt.png").write_bytes(_noise_texture(rng, (52, 52, 56), 6))
    (tex_dir / "concrete.png").write_bytes(_noise_texture(rng, (120, 120, 118), 8))


# ---------------------------------------------------------------------------
# SDF snippets
# ---------------------------------------------------------------------------


def material(color=None, texture=None):
    if texture:
        return (
            "<material><ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>"
            "<pbr><metal>"
            f"<albedo_map>model://city_textures/{texture}</albedo_map>"
            "<roughness>0.85</roughness><metalness>0.0</metalness>"
            "</metal></pbr></material>"
        )
    r, g, b = color
    return (
        f"<material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>"
    )


def static_box(name, x, y, z, sx, sy, sz, mat, yaw=0.0, collide=True):
    geom = f"<geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>"
    collision = (
        f'<collision name="collision">{geom}</collision>' if collide else ""
    )
    return (
        f'    <model name="{name}">\n'
        "      <static>true</static>\n"
        f"      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 {yaw:.3f}</pose>\n"
        '      <link name="link">\n'
        f"        {collision}\n"
        f'        <visual name="visual">{geom}\n'
        f"          {mat}\n"
        "        </visual>\n"
        "      </link>\n"
        "    </model>\n"
    )


def actor_xml(name, visuals, waypoints):
    """Kinematic scripted actor. waypoints: [(t, x, y, yaw)], loops."""
    wp_xml = "".join(
        f"        <waypoint><time>{t:.2f}</time>"
        f"<pose>{x:.3f} {y:.3f} 0 0 0 {yaw:.3f}</pose></waypoint>\n"
        for (t, x, y, yaw) in waypoints
    )
    return (
        f'    <actor name="{name}">\n'
        '      <link name="body">\n'
        f"{visuals}"
        "      </link>\n"
        "      <script>\n"
        "        <loop>true</loop>\n"
        "        <auto_start>true</auto_start>\n"
        '        <trajectory id="0" type="walk">\n'
        f"{wp_xml}"
        "        </trajectory>\n"
        "      </script>\n"
        "    </actor>\n"
    )


def pedestrian_visual(color):
    r, g, b = color
    return (
        '        <visual name="visual">\n'
        "          <pose>0 0 0.75 0 0 0</pose>\n"
        "          <geometry><cylinder><radius>0.15</radius>"
        "<length>1.5</length></cylinder></geometry>\n"
        f"          <material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>\n"
        "        </visual>\n"
    )


def vehicle_visuals(color):
    r, g, b = color
    body = (
        '        <visual name="body">\n'
        "          <pose>0 0 0.12 0 0 0</pose>\n"
        "          <geometry><box><size>0.45 0.25 0.16</size></box></geometry>\n"
        f"          <material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>\n"
        "        </visual>\n"
    )
    cabin = (
        '        <visual name="cabin">\n'
        "          <pose>-0.04 0 0.26 0 0 0</pose>\n"
        "          <geometry><box><size>0.22 0.22 0.12</size></box></geometry>\n"
        "          <material><ambient>0.15 0.18 0.22 1</ambient>"
        "<diffuse>0.15 0.18 0.22 1</diffuse></material>\n"
        "        </visual>\n"
    )
    return body + cabin


# ---------------------------------------------------------------------------
# Route helpers (loops with per-corner turn poses)
# ---------------------------------------------------------------------------


def loop_waypoints(corners, speed, phase=0.0):
    """Timed actor waypoints around a closed polygon.

    Each corner contributes an arrival point (incoming heading) shortly
    before it and a departure point (outgoing heading) at it, so the turn
    happens tightly at the corner instead of smearing along the edge.
    `phase` in [0,1) rotates the schedule so identical circuits desynchronize.
    """
    n = len(corners)
    pts = []  # (x, y, yaw_at_departure)
    total = 0.0
    lengths = []
    for i in range(n):
        x0, y0 = corners[i]
        x1, y1 = corners[(i + 1) % n]
        seg = math.hypot(x1 - x0, y1 - y0)
        lengths.append(seg)
        total += seg

    t = -phase * (total / speed)
    wps = []
    for i in range(n):
        x0, y0 = corners[i]
        x1, y1 = corners[(i + 1) % n]
        yaw_out = math.atan2(y1 - y0, x1 - x0)
        wps.append((t, x0, y0, yaw_out))
        seg = lengths[i]
        pre = max(seg - 0.5, seg * 0.5)
        # arrival point before the next corner, still on incoming heading
        wps.append(
            (
                t + pre / speed,
                x0 + (x1 - x0) * pre / seg,
                y0 + (y1 - y0) * pre / seg,
                yaw_out,
            )
        )
        t += seg / speed
    # close the loop on the first corner's outgoing heading
    x0, y0 = corners[0]
    x1, y1 = corners[1]
    wps.append((t, x0, y0, math.atan2(y1 - y0, x1 - x0)))
    # normalize negative phase times to start at 0
    t0 = wps[0][0]
    return [(t - t0, x, y, yaw) for (t, x, y, yaw) in wps]


def line_waypoints(a, b, speed, dwell=1.0):
    """Back-and-forth walk between two points with a dwell at each end."""
    ax, ay = a
    bx, by = b
    d = math.hypot(bx - ax, by - ay)
    yaw_ab = math.atan2(by - ay, bx - ax)
    yaw_ba = math.atan2(ay - by, ax - bx)
    t1 = d / speed
    return [
        (0.0, ax, ay, yaw_ab),
        (t1, bx, by, yaw_ab),
        (t1 + dwell, bx, by, yaw_ba),
        (2 * t1 + dwell, ax, ay, yaw_ba),
        (2 * t1 + 2 * dwell, ax, ay, yaw_ab),
    ]


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

GUI_TEMPLATE = """    <gui fullscreen="0">
      <plugin filename="MinimalScene" name="3D View">
        <gz-gui>
          <title>3D View</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="string" key="state">docked</property>
        </gz-gui>
        <engine>ogre2</engine>
        <scene>scene</scene>
        <ambient_light>0.4 0.4 0.4</ambient_light>
        <background_color>0.8 0.8 0.8</background_color>
        <camera_pose>{cam_x:.1f} {cam_y:.1f} {cam_z:.1f} 0 0.9 0.78</camera_pose>
      </plugin>
      <plugin filename="GzSceneManager" name="Scene Manager"/>
      <plugin filename="InteractiveViewControl" name="Interactive view"/>
      <plugin filename="CameraTracking" name="Camera Tracking"/>
      <plugin filename="MarkerManager" name="Marker Manager"/>
      <plugin filename="WorldControl" name="World control">
        <gz-gui>
          <title>World control</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property>
          <property type="double" key="height">72</property>
          <property type="double" key="width">121</property>
          <property type="double" key="z">1</property>
          <property type="string" key="state">floating</property>
          <anchors target="3D View">
            <line own="left" target="left"/>
            <line own="bottom" target="bottom"/>
          </anchors>
        </gz-gui>
        <play_pause>true</play_pause>
        <step>true</step>
      </plugin>
      <plugin filename="WorldStats" name="World stats">
        <gz-gui>
          <title>World stats</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property>
          <property type="double" key="height">110</property>
          <property type="double" key="width">290</property>
          <property type="double" key="z">1</property>
          <property type="string" key="state">floating</property>
          <anchors target="3D View">
            <line own="right" target="right"/>
            <line own="bottom" target="bottom"/>
          </anchors>
        </gz-gui>
        <sim_time>true</sim_time>
        <real_time>true</real_time>
        <real_time_factor>true</real_time_factor>
        <iterations>true</iterations>
      </plugin>
      <plugin filename="EntityTree" name="Entity tree">
        <gz-gui>
          <property type="string" key="state">docked_collapsed</property>
        </gz-gui>
      </plugin>
    </gui>
"""

WORLD_SYSTEMS = """    <physics name="1ms" type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.3 0.3 0.3 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
"""


def generate(args):
    rng = random.Random(args.seed)
    blocks = args.blocks
    street = args.street
    block = args.block
    lane = street / 4.0  # right-lane offset from street centerline

    extent = blocks * block + (blocks + 1) * street
    half = extent / 2.0
    # street centerline coordinates (same grid on both axes)
    centers = [-half + street / 2.0 + i * (street + block) for i in range(blocks + 1)]
    # block center coordinates
    block_centers = [-half + street + block / 2.0 + i * (street + block) for i in range(blocks)]

    spawn_row = blocks // 2
    spawn = (centers[0], centers[spawn_row])  # west intersection of the spawn row

    def planner(x, y):
        return (x - spawn[0], y - spawn[1])

    parts = []
    parts.append('<?xml version="1.0" ?>\n<sdf version="1.9">\n')
    parts.append(f'  <world name="limo_city_blocks">\n\n')
    parts.append(
        "    <!-- GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        f"         blocks={blocks}x{blocks} block={block} street={street} "
        f"seed={args.seed} textures={not args.no_textures}\n"
        f"         Robot spawn (planner-frame origin): world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0).\n"
        "         Companion files: config/maps/city_blocks_roadmap.yaml,\n"
        "         config/scenarios/city_patrol.yaml -->\n\n"
    )
    parts.append(GUI_TEMPLATE.format(cam_x=-half - 8, cam_y=-half - 8, cam_z=extent * 0.9))
    parts.append(WORLD_SYSTEMS)

    # Ground plane
    ground_mat = material(color=(0.45, 0.5, 0.45))
    parts.append(
        '    <model name="ground_plane">\n'
        "      <static>true</static>\n"
        '      <link name="link">\n'
        '        <collision name="collision">\n'
        f"          <geometry><plane><normal>0 0 1</normal><size>{extent + 20:.0f} {extent + 20:.0f}</size></plane></geometry>\n"
        "          <surface><friction><ode><mu>0.8</mu><mu2>0.8</mu2></ode></friction></surface>\n"
        "        </collision>\n"
        '        <visual name="visual">\n'
        f"          <geometry><plane><normal>0 0 1</normal><size>{extent + 20:.0f} {extent + 20:.0f}</size></plane></geometry>\n"
        f"          {ground_mat}\n"
        "        </visual>\n"
        "      </link>\n"
        "    </model>\n\n"
    )

    tex = not args.no_textures
    asphalt = material(texture="asphalt.png") if tex else material(color=(0.22, 0.22, 0.24))
    concrete = material(texture="concrete.png") if tex else material(color=(0.5, 0.5, 0.5))

    # Road slabs (visual only — no collision, so no bump at the edges)
    parts.append("    <!-- ============ ROADS ============ -->\n")
    for i, c in enumerate(centers):
        parts.append(
            static_box(f"road_ns_{i}", c, 0, 0.005, street, extent, 0.01, asphalt, collide=False)
        )
        parts.append(
            static_box(f"road_ew_{i}", 0, c, 0.005, extent, street, 0.01, asphalt, collide=False)
        )
    # Center dashes: one thin solid strip per street (kept above the slabs)
    line = material(color=(0.85, 0.75, 0.2))
    for i, c in enumerate(centers):
        parts.append(
            static_box(f"line_ns_{i}", c, 0, 0.011, 0.04, extent, 0.002, line, collide=False)
        )
        parts.append(
            static_box(f"line_ew_{i}", 0, c, 0.011, extent, 0.04, 0.002, line, collide=False)
        )
    parts.append("\n")

    # Perimeter walls
    parts.append("    <!-- ============ PERIMETER ============ -->\n")
    wall_mat = material(color=(0.8, 0.3, 0.1))
    w = half + street / 2.0 + 0.1
    parts.append(static_box("wall_north", 0, w, 0.25, extent + street, 0.2, 0.5, wall_mat))
    parts.append(static_box("wall_south", 0, -w, 0.25, extent + street, 0.2, 0.5, wall_mat))
    parts.append(static_box("wall_east", w, 0, 0.25, 0.2, extent + street, 0.5, wall_mat))
    parts.append(static_box("wall_west", -w, 0, 0.25, 0.2, extent + street, 0.5, wall_mat))
    parts.append("\n")

    # Buildings: each block subdivides into 1, 2, or 4 footprints
    parts.append("    <!-- ============ BUILDINGS ============ -->\n")
    sidewalk = 0.5  # setback from block edge to building face
    n_building = 0
    for bi, bx in enumerate(block_centers):
        for bj, by in enumerate(block_centers):
            usable = block - 2 * sidewalk
            style = rng.choice(["single", "split_x", "split_y", "quad"])
            if style == "single":
                cells = [(bx, by, usable, usable)]
            elif style == "split_x":
                wd = (usable - 0.3) / 2
                cells = [(bx - (wd + 0.3) / 2, by, wd, usable), (bx + (wd + 0.3) / 2, by, wd, usable)]
            elif style == "split_y":
                wd = (usable - 0.3) / 2
                cells = [(bx, by - (wd + 0.3) / 2, usable, wd), (bx, by + (wd + 0.3) / 2, usable, wd)]
            else:
                wd = (usable - 0.3) / 2
                off = (wd + 0.3) / 2
                cells = [
                    (bx - off, by - off, wd, wd),
                    (bx + off, by - off, wd, wd),
                    (bx - off, by + off, wd, wd),
                    (bx + off, by + off, wd, wd),
                ]
            for (cx, cy, sx, sy) in cells:
                h = rng.uniform(0.8, 2.4)
                if tex:
                    mat = material(texture=f"facade_{rng.randrange(len(FACADE_BASES))}.png")
                else:
                    base = rng.choice([(0.55, 0.55, 0.62), (0.65, 0.55, 0.45), (0.5, 0.6, 0.55), (0.6, 0.5, 0.6)])
                    mat = material(color=base)
                parts.append(
                    static_box(f"building_{n_building}", cx, cy, h / 2, sx, sy, h, mat)
                )
                n_building += 1
    # A few concrete street-furniture obstacles (parked boxes) on street edges
    for k in range(blocks):
        c = centers[rng.randrange(len(centers))]
        along = rng.uniform(-half * 0.6, half * 0.6)
        side = rng.choice([-1, 1]) * (street / 2 - 0.25)
        if rng.random() < 0.5:
            parts.append(static_box(f"parked_box_{k}", along, c + side, 0.15, 0.5, 0.3, 0.3, concrete, yaw=rng.uniform(-0.1, 0.1)))
        else:
            parts.append(static_box(f"parked_box_{k}", c + side, along, 0.15, 0.3, 0.5, 0.3, concrete, yaw=rng.uniform(-0.1, 0.1)))
    parts.append("\n")

    # ------------------------------------------------------------------
    # Pedestrian actors
    # ------------------------------------------------------------------
    parts.append("    <!-- ============ PEDESTRIANS (kinematic actors) ============ -->\n")
    ped_colors = [(0.9, 0.75, 0.2), (0.2, 0.55, 0.9), (0.85, 0.3, 0.3), (0.3, 0.8, 0.5)]
    n_ped = 0

    def add_ped(waypoints, speed_desc):
        nonlocal n_ped
        parts.append(
            actor_xml(
                f"ped_{n_ped}_{speed_desc}",
                pedestrian_visual(ped_colors[n_ped % len(ped_colors)]),
                waypoints,
            )
        )
        n_ped += 1

    # (a) street crossers at random interior intersections
    interior = [(i, j) for i in range(len(centers)) for j in range(len(centers))]
    rng.shuffle(interior)
    for (i, j) in interior[: args.peds // 2]:
        cx, cy = centers[i], centers[j]
        speed = rng.uniform(0.35, 0.6)
        reach = street / 2 + 0.7
        if rng.random() < 0.5:
            a, b = (cx - reach, cy + rng.uniform(-0.6, 0.6)), (cx + reach, cy + rng.uniform(-0.6, 0.6))
        else:
            a, b = (cx + rng.uniform(-0.6, 0.6), cy - reach), (cx + rng.uniform(-0.6, 0.6), cy + reach)
        add_ped(line_waypoints(a, b, speed, dwell=rng.uniform(0.5, 2.0)), "cross")

    # (b) sidewalk loopers around random blocks
    for _ in range(args.peds - args.peds // 2):
        bi = rng.randrange(blocks)
        bj = rng.randrange(blocks)
        bx, by = block_centers[bi], block_centers[bj]
        r = block / 2 - 0.25  # sidewalk ring just inside the block edge
        corners = [(bx - r, by - r), (bx + r, by - r), (bx + r, by + r), (bx - r, by + r)]
        if rng.random() < 0.5:
            corners.reverse()
        add_ped(loop_waypoints(corners, rng.uniform(0.4, 0.7), phase=rng.random()), "loop")

    parts.append("\n")

    # ------------------------------------------------------------------
    # Vehicle actors: right-hand traffic, CCW circuits with lane offset
    # ------------------------------------------------------------------
    parts.append("    <!-- ============ VEHICLES (kinematic actors) ============ -->\n")
    veh_colors = [(0.75, 0.15, 0.12), (0.12, 0.35, 0.7), (0.9, 0.6, 0.1), (0.2, 0.6, 0.3), (0.55, 0.2, 0.6)]
    n_veh = 0

    def block_circuit(bi, bj):
        """CCW ring around block (bi,bj), offset outward onto the right lane."""
        x0, x1 = centers[bi], centers[bi + 1]
        y0, y1 = centers[bj], centers[bj + 1]
        return [
            (x0 - lane, y0 - lane),
            (x1 + lane, y0 - lane),
            (x1 + lane, y1 + lane),
            (x0 - lane, y1 + lane),
        ]

    chosen_blocks = [(i, j) for i in range(blocks) for j in range(blocks)]
    rng.shuffle(chosen_blocks)
    for k in range(min(args.vehicles - 1, len(chosen_blocks))):
        bi, bj = chosen_blocks[k]
        speed = rng.uniform(0.45, 0.7)
        wps = loop_waypoints(block_circuit(bi, bj), speed, phase=rng.random())
        parts.append(
            actor_xml(f"vehicle_{n_veh}_block", vehicle_visuals(veh_colors[n_veh % len(veh_colors)]), wps)
        )
        n_veh += 1

    # One ring vehicle on the outer circuit (same CCW direction as the
    # patrol route, so the robot meets it as slow traffic, not head-on).
    ring = [
        (centers[0] - lane, centers[0] - lane),
        (centers[-1] + lane, centers[0] - lane),
        (centers[-1] + lane, centers[-1] + lane),
        (centers[0] - lane, centers[-1] + lane),
    ]
    parts.append(
        actor_xml(
            f"vehicle_{n_veh}_ring",
            vehicle_visuals(veh_colors[n_veh % len(veh_colors)]),
            loop_waypoints(ring, 0.55, phase=0.3),
        )
    )
    n_veh += 1
    parts.append("\n")

    # Robot. The PosePublisher plugin is REQUIRED: the gz-zmq bridge builds
    # its spawn-anchored true pose from /model/limo/pose and silently falls
    # back to drifting wheel odometry without it (a city run accumulated
    # ~1.5m of lateral error that wedged the robot against a building while
    # it believed it was on the street centerline). z=0.075 rests the wheels
    # exactly on the plane so the t=0 physics settle doesn't shift the odom
    # anchor (same as obstacle_gauntlet.sdf).
    parts.append(
        "    <!-- ============ LIMO PRO ROBOT ============ -->\n"
        f"    <!-- Spawn anchors the planner/odom frame: world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0). -->\n"
        "    <include>\n"
        "      <uri>model://limo_pro</uri>\n"
        "      <name>limo</name>\n"
        f"      <pose>{spawn[0]:.3f} {spawn[1]:.3f} 0.075 0 0 0</pose>\n"
        '      <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">\n'
        "        <publish_model_pose>true</publish_model_pose>\n"
        "        <publish_link_pose>false</publish_link_pose>\n"
        "        <publish_collision_pose>false</publish_collision_pose>\n"
        "        <publish_visual_pose>false</publish_visual_pose>\n"
        "        <publish_sensor_pose>false</publish_sensor_pose>\n"
        "        <use_pose_vector_msg>false</use_pose_vector_msg>\n"
        "        <update_frequency>20</update_frequency>\n"
        "      </plugin>\n"
        "    </include>\n\n"
        "  </world>\n</sdf>\n"
    )

    world_path = PROJECT / "simulation" / "worlds" / "city_blocks.sdf"
    world_path.write_text("".join(parts))

    # ------------------------------------------------------------------
    # Roadmap: full street grid in the planner frame
    # ------------------------------------------------------------------
    rm = [
        "# GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        "# Street-grid roadmap for simulation/worlds/city_blocks.sdf.\n"
        "#\n"
        "# Frame note: `planner` = the planning/odom frame, anchored at the robot\n"
        f"# spawn pose in the world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0), so these are\n"
        f"# world coordinates + ({-spawn[0]:.2f}, {-spawn[1]:.2f}).\n"
        "# Select at launch with LIMO_ROADMAP_FILE=config/maps/city_blocks_roadmap.yaml.\n"
        "frame: planner\n"
        "nodes:\n"
    ]
    for i, cx in enumerate(centers):
        for j, cy in enumerate(centers):
            px, py = planner(cx, cy)
            rm.append(f"  - {{id: n{i}_{j}, x: {px:.2f}, y: {py:.2f}}}\n")
    rm.append("links:\n")
    link_width = street - 0.8  # usable width: street minus edge margins
    for i in range(len(centers)):
        for j in range(len(centers)):
            if i + 1 < len(centers):
                rm.append(
                    f"  - {{from: n{i}_{j}, to: n{i + 1}_{j}, width: {link_width:.2f}, speed: {args.street_speed:.2f}}}\n"
                )
            if j + 1 < len(centers):
                rm.append(
                    f"  - {{from: n{i}_{j}, to: n{i}_{j + 1}, width: {link_width:.2f}, speed: {args.street_speed:.2f}}}\n"
                )
    roadmap_path = PROJECT / "config" / "maps" / "city_blocks_roadmap.yaml"
    roadmap_path.write_text("".join(rm))

    # ------------------------------------------------------------------
    # Patrol scenario: outer ring, CCW from the spawn intersection
    # ------------------------------------------------------------------
    last = len(centers) - 1
    ring_nodes = [
        (last, spawn_row, "east_on_spawn_row"),
        (last, last, "northeast_corner"),
        (0, last, "northwest_corner"),
        (0, spawn_row, "home_intersection"),
    ]
    sc = [
        "# GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        "# Continuous city patrol for simulation/worlds/city_blocks.sdf:\n"
        "# counter-clockwise loop around the outer ring, forever (patrol\n"
        "# scenarios re-arm at waypoint 0 after the last waypoint).\n"
        "#\n"
        "# Launch:\n"
        "#   LIMO_ROADMAP_FILE=config/maps/city_blocks_roadmap.yaml \\\n"
        "#   WORLD=$PWD/simulation/worlds/city_blocks.sdf \\\n"
        "#   ./simulation/run_gazebo_full.sh config/scenarios/city_patrol.yaml\n"
        "#\n"
        "# Frame note: planner/odom frame origin is the robot spawn pose in the\n"
        f"# world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0); waypoints below are planner-frame.\n"
        "name: city_patrol\n"
        "scenario_type: patrol\n"
        f"speed_limit: {args.street_speed:.2f}\n"
        "\n"
        "waypoints:\n"
    ]
    for k, (i, j, label) in enumerate(ring_nodes):
        px, py = planner(centers[i], centers[j])
        ni, nj, _ = ring_nodes[(k + 1) % len(ring_nodes)]
        nx, ny = planner(centers[ni], centers[nj])
        theta = math.atan2(ny - py, nx - px)
        sc.append(
            f"  - x: {px:.2f}\n    y: {py:.2f}\n    theta: {theta:.2f}\n"
            f"    tolerance: 0.35\n    speed: {args.patrol_speed:.2f}\n"
            f'    label: "{label}"\n\n'
        )
    scenario_path = PROJECT / "config" / "scenarios" / "city_patrol.yaml"
    scenario_path.write_text("".join(sc))

    # Textures last (skipped with --no-textures)
    if tex:
        write_textures(rng, PROJECT / "simulation" / "models" / "city_textures")

    print(f"world    : {world_path.relative_to(PROJECT)}  ({extent:.0f}x{extent:.0f} m, {n_building} buildings)")
    print(f"actors   : {n_ped} pedestrians, {n_veh} vehicles")
    print(f"roadmap  : {roadmap_path.relative_to(PROJECT)}  ({(blocks + 1) ** 2} nodes)")
    print(f"scenario : {scenario_path.relative_to(PROJECT)}  (patrol ring, loops forever)")
    if tex:
        print("textures : simulation/models/city_textures/ (procedural PBR albedo)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--blocks", type=int, default=3, help="city blocks per side (default 3)")
    ap.add_argument("--block", type=float, default=6.0, help="block size, m (default 6.0)")
    ap.add_argument("--street", type=float, default=3.0, help="street width, m (default 3.0)")
    ap.add_argument("--peds", type=int, default=8, help="pedestrian actors (default 8)")
    ap.add_argument("--vehicles", type=int, default=4, help="vehicle actors incl. ring car (default 4)")
    ap.add_argument("--street-speed", type=float, default=1.0, help="roadmap link speed cap, m/s")
    ap.add_argument("--patrol-speed", type=float, default=0.8, help="patrol waypoint speed, m/s")
    ap.add_argument("--seed", type=int, default=7, help="deterministic layout seed")
    ap.add_argument("--no-textures", action="store_true", help="flat colors instead of PBR textures")
    args = ap.parse_args()
    if args.blocks < 1:
        ap.error("--blocks must be >= 1")
    generate(args)


if __name__ == "__main__":
    main()
