#!/usr/bin/env python3
"""City world generator: grid-of-blocks Gazebo city for the Limo Pro.

The robot is a SIDEWALK robot: it drives the sidewalk ring around each
block and crosses streets on zebra crosswalks, like the pedestrians.
Vehicles (car-sized, ~3.5x the robot's length) own the roads.

Emits four mutually consistent artifacts from one parameter set:

  simulation/worlds/city_blocks.sdf         world: roads, sidewalks,
                                            crosswalks, buildings, walls,
                                            pedestrian + vehicle actors
  simulation/models/city_textures/          procedural PBR albedo maps
  config/maps/city_blocks_roadmap.yaml      SIDEWALK + CROSSWALK roadmap
                                            (planner frame = world - spawn)
  config/scenarios/city_patrol.yaml         looping patrol around the city
                                            perimeter sidewalks

Layout: (blocks x blocks) city blocks separated by streets. Each block
carries a sidewalk ring (width --sidewalk) between the buildings and the
street; adjacent blocks connect via zebra crosswalks near every interior
intersection. Roadmap nodes are the 4 sidewalk-ring corners of every
block; links are sidewalk edges + crosswalks. The robot spawns at the
south-west corner node of block (0,0), facing east, which anchors the
planner frame. Everything is limo-scale (~1/10 of a real city).

Actors are kinematic (no collision geometry) but visible to the gpu_lidar,
so the stack must avoid them perceptually. Vehicles keep right-hand
traffic: each loops its circuit counter-clockwise with a right-lane
offset, conflicting with the robot only at crosswalks — the interesting
encounter this world is built around.

Usage:
  python3 simulation/gen_city_world.py            # defaults (3x3, seed 7)
  python3 simulation/gen_city_world.py --blocks 4 --seed 3 --no-textures
"""

import argparse
import math
import random
import struct
import zlib
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Procedural PNG textures (stdlib-only PNG writer)
# ---------------------------------------------------------------------------


def _png_bytes(width, height, rgb_rows):
    """Encode 8-bit RGB rows (list of bytearrays) as a PNG file."""

    def chunk(tag, data):
        block = tag + data
        return struct.pack(">I", len(data)) + block + struct.pack(
            ">I", zlib.crc32(block) & 0xFFFFFFFF
        )

    raw = b"".join(b"\x00" + bytes(row) for row in rgb_rows)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 6))
        + chunk(b"IEND", b"")
    )


def _facade_texture(rng, base, size=256, cols=6, rows=8):
    """Building facade: base wall color with a grid of windows, some lit."""
    rows_px = []
    cell_w, cell_h = size // cols, size // rows
    win_margin_x, win_margin_y = cell_w // 4, cell_h // 4
    lit = {
        (c, r)
        for c in range(cols)
        for r in range(rows)
        if rng.random() < 0.18
    }
    for y in range(size):
        row = bytearray()
        for x in range(size):
            c, r = x // cell_w, y // cell_h
            in_win = (
                c < cols
                and r < rows
                and win_margin_x <= x - c * cell_w < cell_w - win_margin_x
                and win_margin_y <= y - r * cell_h < cell_h - win_margin_y
            )
            if in_win:
                px = (245, 220, 130) if (c, r) in lit else (38, 52, 70)
            else:
                n = rng.randint(-6, 6)
                px = tuple(max(0, min(255, v + n)) for v in base)
            row.extend(px)
        rows_px.append(row)
    return _png_bytes(size, size, rows_px)


def _noise_texture(rng, base, spread, size=256):
    """Flat noisy surface (asphalt, concrete, paving)."""
    rows_px = []
    for _ in range(size):
        row = bytearray()
        for _ in range(size):
            n = rng.randint(-spread, spread)
            row.extend(max(0, min(255, v + n)) for v in base)
        rows_px.append(row)
    return _png_bytes(size, size, rows_px)


FACADE_BASES = [
    (168, 148, 122),  # sandstone
    (140, 148, 158),  # steel gray
    (150, 118, 100),  # brick brown
    (128, 142, 128),  # sage
    (172, 160, 150),  # limestone
]


def write_textures(rng, tex_dir):
    tex_dir.mkdir(parents=True, exist_ok=True)
    (tex_dir / "model.config").write_text(
        '<?xml version="1.0"?>\n'
        "<model>\n"
        "  <name>city_textures</name>\n"
        "  <version>1.0</version>\n"
        "  <description>Procedural textures for city_blocks.sdf "
        "(generated by gen_city_world.py)</description>\n"
        "</model>\n"
    )
    for i, base in enumerate(FACADE_BASES):
        (tex_dir / f"facade_{i}.png").write_bytes(_facade_texture(rng, base))
    (tex_dir / "asphalt.png").write_bytes(_noise_texture(rng, (52, 52, 56), 6))
    (tex_dir / "concrete.png").write_bytes(_noise_texture(rng, (120, 120, 118), 8))
    (tex_dir / "paving.png").write_bytes(_noise_texture(rng, (148, 144, 136), 10))


# ---------------------------------------------------------------------------
# SDF snippets
# ---------------------------------------------------------------------------


def material(color=None, texture=None):
    if texture:
        return (
            "<material><ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>"
            "<pbr><metal>"
            f"<albedo_map>model://city_textures/{texture}</albedo_map>"
            "<roughness>0.85</roughness><metalness>0.0</metalness>"
            "</metal></pbr></material>"
        )
    r, g, b = color
    return (
        f"<material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>"
    )


def static_box(name, x, y, z, sx, sy, sz, mat, yaw=0.0, collide=True):
    geom = f"<geometry><box><size>{sx:.3f} {sy:.3f} {sz:.3f}</size></box></geometry>"
    collision = (
        f'<collision name="collision">{geom}</collision>' if collide else ""
    )
    return (
        f'    <model name="{name}">\n'
        "      <static>true</static>\n"
        f"      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 {yaw:.3f}</pose>\n"
        '      <link name="link">\n'
        f"        {collision}\n"
        f'        <visual name="visual">{geom}\n'
        f"          {mat}\n"
        "        </visual>\n"
        "      </link>\n"
        "    </model>\n"
    )


def actor_xml(name, visuals, waypoints):
    """Kinematic scripted actor. waypoints: [(t, x, y, yaw)], loops."""
    wp_xml = "".join(
        f"        <waypoint><time>{t:.2f}</time>"
        f"<pose>{x:.3f} {y:.3f} 0 0 0 {yaw:.3f}</pose></waypoint>\n"
        for (t, x, y, yaw) in waypoints
    )
    return (
        f'    <actor name="{name}">\n'
        '      <link name="body">\n'
        f"{visuals}"
        "      </link>\n"
        "      <script>\n"
        "        <loop>true</loop>\n"
        "        <auto_start>true</auto_start>\n"
        '        <trajectory id="0" type="walk">\n'
        f"{wp_xml}"
        "        </trajectory>\n"
        "      </script>\n"
        "    </actor>\n"
    )


def pedestrian_visual(color):
    r, g, b = color
    return (
        '        <visual name="visual">\n'
        "          <pose>0 0 0.75 0 0 0</pose>\n"
        "          <geometry><cylinder><radius>0.15</radius>"
        "<length>1.5</length></cylinder></geometry>\n"
        f"          <material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>\n"
        "        </visual>\n"
    )


def vehicle_visuals(color):
    """Car-sized vehicle (~3.5x the Limo's length at this scale)."""
    r, g, b = color
    body = (
        '        <visual name="body">\n'
        "          <pose>0 0 0.16 0 0 0</pose>\n"
        "          <geometry><box><size>1.10 0.55 0.32</size></box></geometry>\n"
        f"          <material><ambient>{r} {g} {b} 1</ambient>"
        f"<diffuse>{r} {g} {b} 1</diffuse></material>\n"
        "        </visual>\n"
    )
    cabin = (
        '        <visual name="cabin">\n'
        "          <pose>-0.08 0 0.44 0 0 0</pose>\n"
        "          <geometry><box><size>0.55 0.48 0.24</size></box></geometry>\n"
        "          <material><ambient>0.15 0.18 0.22 1</ambient>"
        "<diffuse>0.15 0.18 0.22 1</diffuse></material>\n"
        "        </visual>\n"
    )
    return body + cabin


# ---------------------------------------------------------------------------
# Route helpers (loops with per-corner turn poses)
# ---------------------------------------------------------------------------


def loop_waypoints(corners, speed, phase=0.0, corner_cut=0.5):
    """Timed actor waypoints around a closed polygon.

    Each corner contributes an arrival point (incoming heading) shortly
    before it and a departure point (outgoing heading) at it, so the turn
    happens tightly at the corner instead of smearing along the edge.
    `phase` in [0,1) rotates the START POSE around the polygon so identical
    circuits desynchronize spatially, not just in schedule. `corner_cut`
    grows with vehicle length so long bodies swing wider into turns.
    """
    n = len(corners)
    lengths = []
    total = 0.0
    for i in range(n):
        x0, y0 = corners[i]
        x1, y1 = corners[(i + 1) % n]
        seg = math.hypot(x1 - x0, y1 - y0)
        lengths.append(seg)
        total += seg

    # Spatial phase: rotate the corner list so the actor STARTS partway
    # around the loop (at the corner nearest the phase arc position).
    if phase:
        arc, target = 0.0, phase * total
        start = 0
        for i in range(n):
            if arc >= target:
                start = i
                break
            arc += lengths[i]
        corners = corners[start:] + corners[:start]
        lengths = lengths[start:] + lengths[:start]

    t = 0.0
    wps = []
    for i in range(n):
        x0, y0 = corners[i]
        x1, y1 = corners[(i + 1) % n]
        yaw_out = math.atan2(y1 - y0, x1 - x0)
        wps.append((t, x0, y0, yaw_out))
        seg = lengths[i]
        pre = max(seg - corner_cut, seg * 0.5)
        wps.append(
            (
                t + pre / speed,
                x0 + (x1 - x0) * pre / seg,
                y0 + (y1 - y0) * pre / seg,
                yaw_out,
            )
        )
        t += seg / speed
    x0, y0 = corners[0]
    x1, y1 = corners[1]
    wps.append((t, x0, y0, math.atan2(y1 - y0, x1 - x0)))
    return wps


def line_waypoints(a, b, speed, dwell=1.0):
    """Back-and-forth walk between two points with a dwell at each end."""
    ax, ay = a
    bx, by = b
    d = math.hypot(bx - ax, by - ay)
    yaw_ab = math.atan2(by - ay, bx - ax)
    yaw_ba = math.atan2(ay - by, ax - bx)
    t1 = d / speed
    return [
        (0.0, ax, ay, yaw_ab),
        (t1, bx, by, yaw_ab),
        (t1 + dwell, bx, by, yaw_ba),
        (2 * t1 + dwell, ax, ay, yaw_ba),
        (2 * t1 + 2 * dwell, ax, ay, yaw_ab),
    ]


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

GUI_TEMPLATE = """    <gui fullscreen="0">
      <plugin filename="MinimalScene" name="3D View">
        <gz-gui>
          <title>3D View</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="string" key="state">docked</property>
        </gz-gui>
        <engine>ogre2</engine>
        <scene>scene</scene>
        <ambient_light>0.4 0.4 0.4</ambient_light>
        <background_color>0.8 0.8 0.8</background_color>
        <camera_pose>{cam_x:.1f} {cam_y:.1f} {cam_z:.1f} 0 0.9 0.78</camera_pose>
      </plugin>
      <plugin filename="GzSceneManager" name="Scene Manager"/>
      <plugin filename="InteractiveViewControl" name="Interactive view"/>
      <plugin filename="CameraTracking" name="Camera Tracking"/>
      <plugin filename="MarkerManager" name="Marker Manager"/>
      <plugin filename="WorldControl" name="World control">
        <gz-gui>
          <title>World control</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property>
          <property type="double" key="height">72</property>
          <property type="double" key="width">121</property>
          <property type="double" key="z">1</property>
          <property type="string" key="state">floating</property>
          <anchors target="3D View">
            <line own="left" target="left"/>
            <line own="bottom" target="bottom"/>
          </anchors>
        </gz-gui>
        <play_pause>true</play_pause>
        <step>true</step>
      </plugin>
      <plugin filename="WorldStats" name="World stats">
        <gz-gui>
          <title>World stats</title>
          <property type="bool" key="showTitleBar">false</property>
          <property type="bool" key="resizable">false</property>
          <property type="double" key="height">110</property>
          <property type="double" key="width">290</property>
          <property type="double" key="z">1</property>
          <property type="string" key="state">floating</property>
          <anchors target="3D View">
            <line own="right" target="right"/>
            <line own="bottom" target="bottom"/>
          </anchors>
        </gz-gui>
        <sim_time>true</sim_time>
        <real_time>true</real_time>
        <real_time_factor>true</real_time_factor>
        <iterations>true</iterations>
      </plugin>
      <plugin filename="EntityTree" name="Entity tree">
        <gz-gui>
          <property type="string" key="state">docked_collapsed</property>
        </gz-gui>
      </plugin>
    </gui>
"""

WORLD_SYSTEMS = """    <physics name="1ms" type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.3 0.3 0.3 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
"""

CORNER_TAGS = ["sw", "se", "ne", "nw"]


def generate(args):
    rng = random.Random(args.seed)
    blocks = args.blocks
    street = args.street
    block = args.block
    sidewalk = args.sidewalk
    lane = street / 4.0  # right-lane offset from street centerline

    extent = blocks * block + (blocks + 1) * street
    half = extent / 2.0
    centers = [-half + street / 2.0 + i * (street + block) for i in range(blocks + 1)]
    block_centers = [-half + street + block / 2.0 + i * (street + block) for i in range(blocks)]

    # Sidewalk-ring corner nodes: the roadmap graph vertices.
    rh = block / 2.0 - sidewalk / 2.0  # ring half-extent from block center
    corner = {}  # (bi, bj, tag) -> world (x, y)
    for bi, bx in enumerate(block_centers):
        for bj, by in enumerate(block_centers):
            corner[(bi, bj, "sw")] = (bx - rh, by - rh)
            corner[(bi, bj, "se")] = (bx + rh, by - rh)
            corner[(bi, bj, "ne")] = (bx + rh, by + rh)
            corner[(bi, bj, "nw")] = (bx - rh, by + rh)

    # Crosswalk links between adjacent blocks (interior streets only —
    # perimeter streets have nothing on their far side).
    crosswalks = []  # (keyA, keyB) of corner dict keys
    for i in range(1, blocks):  # vertical street i between columns i-1, i
        for j in range(blocks):
            crosswalks.append(((i - 1, j, "se"), (i, j, "sw")))
            crosswalks.append(((i - 1, j, "ne"), (i, j, "nw")))
    for j in range(1, blocks):  # horizontal street j between rows j-1, j
        for i in range(blocks):
            crosswalks.append(((i, j - 1, "nw"), (i, j, "sw")))
            crosswalks.append(((i, j - 1, "ne"), (i, j, "se")))

    # Robot spawn: SW corner node of block (0,0), facing east.
    spawn = corner[(0, 0, "sw")]

    def planner(x, y):
        return (x - spawn[0], y - spawn[1])

    parts = []
    parts.append('<?xml version="1.0" ?>\n<sdf version="1.9">\n')
    parts.append('  <world name="limo_city_blocks">\n\n')
    parts.append(
        "    <!-- GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        f"         blocks={blocks}x{blocks} block={block} street={street} "
        f"sidewalk={sidewalk} seed={args.seed} textures={not args.no_textures}\n"
        "         Sidewalk-robot world: the robot navigates sidewalk rings +\n"
        "         zebra crosswalks; car-sized vehicle actors own the roads.\n"
        f"         Robot spawn (planner-frame origin): world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0).\n"
        "         Companion files: config/maps/city_blocks_roadmap.yaml,\n"
        "         config/scenarios/city_patrol.yaml -->\n\n"
    )
    parts.append(GUI_TEMPLATE.format(cam_x=-half - 8, cam_y=-half - 8, cam_z=extent * 0.9))
    parts.append(WORLD_SYSTEMS)

    ground_mat = material(color=(0.45, 0.5, 0.45))
    parts.append(
        '    <model name="ground_plane">\n'
        "      <static>true</static>\n"
        '      <link name="link">\n'
        '        <collision name="collision">\n'
        f"          <geometry><plane><normal>0 0 1</normal><size>{extent + 20:.0f} {extent + 20:.0f}</size></plane></geometry>\n"
        "          <surface><friction><ode><mu>0.8</mu><mu2>0.8</mu2></ode></friction></surface>\n"
        "        </collision>\n"
        '        <visual name="visual">\n'
        f"          <geometry><plane><normal>0 0 1</normal><size>{extent + 20:.0f} {extent + 20:.0f}</size></plane></geometry>\n"
        f"          {ground_mat}\n"
        "        </visual>\n"
        "      </link>\n"
        "    </model>\n\n"
    )

    tex = not args.no_textures
    asphalt = material(texture="asphalt.png") if tex else material(color=(0.22, 0.22, 0.24))
    concrete = material(texture="concrete.png") if tex else material(color=(0.5, 0.5, 0.5))
    paving = material(texture="paving.png") if tex else material(color=(0.58, 0.57, 0.53))

    # Road slabs + lane lines (visual only)
    parts.append("    <!-- ============ ROADS ============ -->\n")
    for i, c in enumerate(centers):
        parts.append(
            static_box(f"road_ns_{i}", c, 0, 0.005, street, extent, 0.01, asphalt, collide=False)
        )
        parts.append(
            static_box(f"road_ew_{i}", 0, c, 0.005, extent, street, 0.01, asphalt, collide=False)
        )
    line = material(color=(0.85, 0.75, 0.2))
    for i, c in enumerate(centers):
        parts.append(
            static_box(f"line_ns_{i}", c, 0, 0.011, 0.04, extent, 0.002, line, collide=False)
        )
        parts.append(
            static_box(f"line_ew_{i}", 0, c, 0.011, extent, 0.04, 0.002, line, collide=False)
        )
    parts.append("\n")

    # Sidewalk paving rings (visual only; N/S slabs full width, E/W slabs
    # shortened between them so overlapping same-z slabs don't z-fight)
    parts.append("    <!-- ============ SIDEWALKS ============ -->\n")
    for bi, bx in enumerate(block_centers):
        for bj, by in enumerate(block_centers):
            s_off = block / 2.0 - sidewalk / 2.0
            parts.append(static_box(f"walk_s_{bi}_{bj}", bx, by - s_off, 0.008, block, sidewalk, 0.012, paving, collide=False))
            parts.append(static_box(f"walk_n_{bi}_{bj}", bx, by + s_off, 0.008, block, sidewalk, 0.012, paving, collide=False))
            inner = block - 2 * sidewalk
            parts.append(static_box(f"walk_w_{bi}_{bj}", bx - s_off, by, 0.008, sidewalk, inner, 0.012, paving, collide=False))
            parts.append(static_box(f"walk_e_{bi}_{bj}", bx + s_off, by, 0.008, sidewalk, inner, 0.012, paving, collide=False))
    parts.append("\n")

    # Zebra crosswalk stripes (visual only), one band per crosswalk link,
    # drawn across the street span between the two corner nodes.
    parts.append("    <!-- ============ CROSSWALKS ============ -->\n")
    stripe = material(color=(0.92, 0.92, 0.92))
    for k, (ka, kb) in enumerate(crosswalks):
        ax, ay = corner[ka]
        bx2, by2 = corner[kb]
        if abs(ay - by2) < 1e-6:  # crossing a vertical street, walking in x
            cx = (ax + bx2) / 2.0
            n_str = max(4, int(street / 0.5))
            for s in range(n_str):
                sx = cx - street / 2.0 + (s + 0.5) * street / n_str
                parts.append(
                    static_box(f"zebra_{k}_{s}", sx, ay, 0.013, 0.16, 0.5, 0.002, stripe, collide=False)
                )
        else:  # crossing a horizontal street, walking in y
            cy = (ay + by2) / 2.0
            n_str = max(4, int(street / 0.5))
            for s in range(n_str):
                sy = cy - street / 2.0 + (s + 0.5) * street / n_str
                parts.append(
                    static_box(f"zebra_{k}_{s}", ax, sy, 0.013, 0.5, 0.16, 0.002, stripe, collide=False)
                )
    parts.append("\n")

    # Perimeter walls
    parts.append("    <!-- ============ PERIMETER ============ -->\n")
    wall_mat = material(color=(0.8, 0.3, 0.1))
    w = half + street / 2.0 + 0.1
    parts.append(static_box("wall_north", 0, w, 0.25, extent + street, 0.2, 0.5, wall_mat))
    parts.append(static_box("wall_south", 0, -w, 0.25, extent + street, 0.2, 0.5, wall_mat))
    parts.append(static_box("wall_east", w, 0, 0.25, 0.2, extent + street, 0.5, wall_mat))
    parts.append(static_box("wall_west", -w, 0, 0.25, 0.2, extent + street, 0.5, wall_mat))
    parts.append("\n")

    # Buildings: inset behind the sidewalk ring; 1, 2, or 4 per block
    parts.append("    <!-- ============ BUILDINGS ============ -->\n")
    n_building = 0
    for bi, bx in enumerate(block_centers):
        for bj, by in enumerate(block_centers):
            usable = block - 2 * sidewalk - 0.2
            style = rng.choice(["single", "split_x", "split_y", "quad"])
            if style == "single":
                cells = [(bx, by, usable, usable)]
            elif style == "split_x":
                wd = (usable - 0.3) / 2
                cells = [(bx - (wd + 0.3) / 2, by, wd, usable), (bx + (wd + 0.3) / 2, by, wd, usable)]
            elif style == "split_y":
                wd = (usable - 0.3) / 2
                cells = [(bx, by - (wd + 0.3) / 2, usable, wd), (bx, by + (wd + 0.3) / 2, usable, wd)]
            else:
                wd = (usable - 0.3) / 2
                off = (wd + 0.3) / 2
                cells = [
                    (bx - off, by - off, wd, wd),
                    (bx + off, by - off, wd, wd),
                    (bx - off, by + off, wd, wd),
                    (bx + off, by + off, wd, wd),
                ]
            for (cx, cy, sx, sy) in cells:
                h = rng.uniform(0.8, 2.4)
                if tex:
                    mat = material(texture=f"facade_{rng.randrange(len(FACADE_BASES))}.png")
                else:
                    base = rng.choice([(0.55, 0.55, 0.62), (0.65, 0.55, 0.45), (0.5, 0.6, 0.55), (0.6, 0.5, 0.6)])
                    mat = material(color=base)
                parts.append(
                    static_box(f"building_{n_building}", cx, cy, h / 2, sx, sy, h, mat)
                )
                n_building += 1
    # Street-edge parked obstacles (in the road, not on sidewalks)
    for k in range(blocks):
        c = centers[rng.randrange(len(centers))]
        along = rng.uniform(-half * 0.6, half * 0.6)
        side = rng.choice([-1, 1]) * (street / 2 - 0.35)
        if rng.random() < 0.5:
            parts.append(static_box(f"parked_box_{k}", along, c + side, 0.15, 0.6, 0.35, 0.3, concrete, yaw=rng.uniform(-0.1, 0.1)))
        else:
            parts.append(static_box(f"parked_box_{k}", c + side, along, 0.15, 0.35, 0.6, 0.3, concrete, yaw=rng.uniform(-0.1, 0.1)))
    parts.append("\n")

    # ------------------------------------------------------------------
    # Pedestrian actors: sidewalk loopers + crosswalk crossers, sharing
    # exactly the network the robot navigates.
    # ------------------------------------------------------------------
    parts.append("    <!-- ============ PEDESTRIANS (kinematic actors) ============ -->\n")
    ped_colors = [(0.9, 0.75, 0.2), (0.2, 0.55, 0.9), (0.85, 0.3, 0.3), (0.3, 0.8, 0.5)]
    n_ped = 0

    def add_ped(waypoints, kind):
        nonlocal n_ped
        parts.append(
            actor_xml(
                f"ped_{n_ped}_{kind}",
                pedestrian_visual(ped_colors[n_ped % len(ped_colors)]),
                waypoints,
            )
        )
        n_ped += 1

    # (a) crosswalk crossers on random crosswalks
    xw_pool = crosswalks[:]
    rng.shuffle(xw_pool)
    for (ka, kb) in xw_pool[: args.peds // 2]:
        speed = rng.uniform(0.35, 0.6)
        add_ped(line_waypoints(corner[ka], corner[kb], speed, dwell=rng.uniform(0.5, 2.0)), "cross")

    # (b) sidewalk loopers around random blocks (the robot's own rings)
    for _ in range(args.peds - args.peds // 2):
        bi = rng.randrange(blocks)
        bj = rng.randrange(blocks)
        bx, by = block_centers[bi], block_centers[bj]
        pr = block / 2.0 - sidewalk / 2.0 - 0.3  # inside the robot line
        ring = [(bx - pr, by - pr), (bx + pr, by - pr), (bx + pr, by + pr), (bx - pr, by + pr)]
        if rng.random() < 0.5:
            ring.reverse()
        add_ped(loop_waypoints(ring, rng.uniform(0.4, 0.7), phase=rng.random()), "loop")

    parts.append("\n")

    # ------------------------------------------------------------------
    # Vehicle actors: car-sized, right-hand traffic, CCW circuits with
    # lane offset. They conflict with the robot only at crosswalks.
    # ------------------------------------------------------------------
    parts.append("    <!-- ============ VEHICLES (kinematic actors) ============ -->\n")
    veh_colors = [(0.75, 0.15, 0.12), (0.12, 0.35, 0.7), (0.9, 0.6, 0.1), (0.2, 0.6, 0.3), (0.55, 0.2, 0.6)]
    n_veh = 0

    def block_circuit(bi, bj):
        x0, x1 = centers[bi], centers[bi + 1]
        y0, y1 = centers[bj], centers[bj + 1]
        return [
            (x0 - lane, y0 - lane),
            (x1 + lane, y0 - lane),
            (x1 + lane, y1 + lane),
            (x0 - lane, y1 + lane),
        ]

    chosen_blocks = [(i, j) for i in range(blocks) for j in range(blocks)]
    rng.shuffle(chosen_blocks)
    for k in range(min(args.vehicles - 1, len(chosen_blocks))):
        bi, bj = chosen_blocks[k]
        speed = rng.uniform(0.35, 0.55)
        wps = loop_waypoints(block_circuit(bi, bj), speed, phase=rng.random(), corner_cut=0.9)
        parts.append(
            actor_xml(f"vehicle_{n_veh}_block", vehicle_visuals(veh_colors[n_veh % len(veh_colors)]), wps)
        )
        n_veh += 1

    ring = [
        (centers[0] - lane, centers[0] - lane),
        (centers[-1] + lane, centers[0] - lane),
        (centers[-1] + lane, centers[-1] + lane),
        (centers[0] - lane, centers[-1] + lane),
    ]
    parts.append(
        actor_xml(
            f"vehicle_{n_veh}_ring",
            vehicle_visuals(veh_colors[n_veh % len(veh_colors)]),
            loop_waypoints(ring, 0.45, phase=0.3, corner_cut=0.9),
        )
    )
    n_veh += 1
    parts.append("\n")

    # Robot. The PosePublisher plugin is REQUIRED: the gz-zmq bridge builds
    # its spawn-anchored true pose from /model/limo/pose and silently falls
    # back to drifting wheel odometry without it. z=0.075 rests the wheels
    # exactly on the plane so the t=0 physics settle doesn't shift the odom
    # anchor (same as obstacle_gauntlet.sdf).
    parts.append(
        "    <!-- ============ LIMO PRO ROBOT (sidewalk robot) ============ -->\n"
        f"    <!-- Spawn anchors the planner/odom frame: world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0). -->\n"
        "    <include>\n"
        "      <uri>model://limo_pro</uri>\n"
        "      <name>limo</name>\n"
        f"      <pose>{spawn[0]:.3f} {spawn[1]:.3f} 0.075 0 0 0</pose>\n"
        '      <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">\n'
        "        <publish_model_pose>true</publish_model_pose>\n"
        "        <publish_link_pose>false</publish_link_pose>\n"
        "        <publish_collision_pose>false</publish_collision_pose>\n"
        "        <publish_visual_pose>false</publish_visual_pose>\n"
        "        <publish_sensor_pose>false</publish_sensor_pose>\n"
        "        <use_pose_vector_msg>false</use_pose_vector_msg>\n"
        "        <update_frequency>20</update_frequency>\n"
        "      </plugin>\n"
        "    </include>\n\n"
        "  </world>\n</sdf>\n"
    )

    world_path = PROJECT / "simulation" / "worlds" / "city_blocks.sdf"
    world_path.write_text("".join(parts))

    # ------------------------------------------------------------------
    # Roadmap: sidewalk rings + crosswalks in the planner frame
    # ------------------------------------------------------------------
    def node_id(key):
        bi, bj, tag = key
        return f"b{bi}_{bj}_{tag}"

    rm = [
        "# GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        "# Sidewalk + crosswalk roadmap for simulation/worlds/city_blocks.sdf:\n"
        "# nodes are sidewalk-ring corners of every block; links are sidewalk\n"
        "# edges and zebra crosswalks (the robot is a sidewalk robot).\n"
        "#\n"
        "# Frame note: `planner` = the planning/odom frame, anchored at the robot\n"
        f"# spawn pose in the world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0), so these are\n"
        f"# world coordinates + ({-spawn[0]:.2f}, {-spawn[1]:.2f}).\n"
        "# Select at launch with LIMO_ROADMAP_FILE=config/maps/city_blocks_roadmap.yaml.\n"
        "frame: planner\n"
        "nodes:\n"
    ]
    for key in sorted(corner):
        px, py = planner(*corner[key])
        rm.append(f"  - {{id: {node_id(key)}, x: {px:.2f}, y: {py:.2f}}}\n")
    rm.append("links:\n")
    walk_width = max(sidewalk - 0.2, 0.6)
    for bi in range(blocks):
        for bj in range(blocks):
            ring = [(bi, bj, t) for t in CORNER_TAGS]
            for a, b in zip(ring, ring[1:] + ring[:1]):
                rm.append(
                    f"  - {{from: {node_id(a)}, to: {node_id(b)}, width: {walk_width:.2f}, speed: {args.sidewalk_speed:.2f}}}\n"
                )
    for (ka, kb) in crosswalks:
        rm.append(
            f"  - {{from: {node_id(ka)}, to: {node_id(kb)}, width: {walk_width:.2f}, speed: {args.crosswalk_speed:.2f}}}\n"
        )
    roadmap_path = PROJECT / "config" / "maps" / "city_blocks_roadmap.yaml"
    roadmap_path.write_text("".join(rm))

    # ------------------------------------------------------------------
    # Patrol scenario: city-perimeter sidewalk loop through the outer
    # corner nodes (routes through sidewalks + crosswalks automatically)
    # ------------------------------------------------------------------
    last = blocks - 1
    ring_nodes = [
        ((last, 0, "se"), "southeast_corner"),
        ((last, last, "ne"), "northeast_corner"),
        ((0, last, "nw"), "northwest_corner"),
        ((0, 0, "sw"), "home_corner"),
    ]
    sc = [
        "# GENERATED by simulation/gen_city_world.py — do not edit by hand.\n"
        "# Continuous sidewalk patrol for simulation/worlds/city_blocks.sdf:\n"
        "# counter-clockwise loop around the city perimeter sidewalks,\n"
        "# crossing streets on zebra crosswalks, forever (patrol scenarios\n"
        "# re-arm at waypoint 0 after the last waypoint).\n"
        "#\n"
        "# Launch:\n"
        "#   LIMO_ROADMAP_FILE=config/maps/city_blocks_roadmap.yaml \\\n"
        "#   WORLD=$PWD/simulation/worlds/city_blocks.sdf \\\n"
        "#   ./simulation/run_gazebo_full.sh config/scenarios/city_patrol.yaml\n"
        "#\n"
        "# Frame note: planner/odom frame origin is the robot spawn pose in the\n"
        f"# world ({spawn[0]:.2f}, {spawn[1]:.2f}, yaw 0); waypoints below are planner-frame.\n"
        "name: city_patrol\n"
        "scenario_type: patrol\n"
        f"speed_limit: {args.sidewalk_speed:.2f}\n"
        "\n"
        "waypoints:\n"
    ]
    for k, (key, label) in enumerate(ring_nodes):
        px, py = planner(*corner[key])
        nkey, _ = ring_nodes[(k + 1) % len(ring_nodes)]
        nx, ny = planner(*corner[nkey])
        theta = math.atan2(ny - py, nx - px)
        sc.append(
            f"  - x: {px:.2f}\n    y: {py:.2f}\n    theta: {theta:.2f}\n"
            f"    tolerance: 0.35\n    speed: {args.patrol_speed:.2f}\n"
            f'    label: "{label}"\n\n'
        )
    scenario_path = PROJECT / "config" / "scenarios" / "city_patrol.yaml"
    scenario_path.write_text("".join(sc))

    if tex:
        write_textures(rng, PROJECT / "simulation" / "models" / "city_textures")

    n_nodes = len(corner)
    n_links = blocks * blocks * 4 + len(crosswalks)
    print(f"world    : {world_path.relative_to(PROJECT)}  ({extent:.0f}x{extent:.0f} m, {n_building} buildings, {len(crosswalks)} crosswalks)")
    print(f"actors   : {n_ped} pedestrians, {n_veh} car-sized vehicles")
    print(f"roadmap  : {roadmap_path.relative_to(PROJECT)}  ({n_nodes} nodes, {n_links} links, sidewalk+crosswalk)")
    print(f"scenario : {scenario_path.relative_to(PROJECT)}  (perimeter sidewalk patrol, loops forever)")
    if tex:
        print("textures : simulation/models/city_textures/ (procedural PBR albedo)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--blocks", type=int, default=3, help="city blocks per side (default 3)")
    ap.add_argument("--block", type=float, default=7.0, help="block size, m (default 7.0)")
    ap.add_argument("--street", type=float, default=3.0, help="street width, m (default 3.0)")
    ap.add_argument("--sidewalk", type=float, default=1.5, help="sidewalk width, m (default 1.5)")
    ap.add_argument("--peds", type=int, default=8, help="pedestrian actors (default 8)")
    ap.add_argument("--vehicles", type=int, default=4, help="vehicle actors incl. ring car (default 4)")
    ap.add_argument("--sidewalk-speed", type=float, default=0.8, help="roadmap sidewalk speed cap, m/s")
    ap.add_argument("--crosswalk-speed", type=float, default=0.7, help="roadmap crosswalk speed cap, m/s")
    ap.add_argument("--patrol-speed", type=float, default=0.6, help="patrol waypoint speed, m/s")
    ap.add_argument("--seed", type=int, default=7, help="deterministic layout seed")
    ap.add_argument("--no-textures", action="store_true", help="flat colors instead of PBR textures")
    args = ap.parse_args()
    if args.blocks < 1:
        ap.error("--blocks must be >= 1")
    if args.sidewalk >= args.block / 2:
        ap.error("--sidewalk must be < block/2")
    generate(args)


if __name__ == "__main__":
    main()
